version: '3.8'
services:
  eureka-server:
    image: axeldamage/fullstack-ss-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  pet-service:
    image: openjdk:17
    container_name: pet-service
    ports:
      - "3001:3001"
    volumes:
      - /tmp/pet-service.jar:/app/app.jar
    command: java -jar /app/app.jar
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    restart: unless-stopped
  geo-service:
    image: openjdk:17
    container_name: geo-service
    ports:
      - "3002:3002"
    volumes:
      - /tmp/geo-service.jar:/app/app.jar
    command: java -jar /app/app.jar
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    restart: unless-stopped
  match-service:
    image: openjdk:17
    container_name: match-service
    ports:
      - "3003:3003"
    volumes:
      - /tmp/match-service.jar:/app/app.jar
    command: java -jar /app/app.jar
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    restart: unless-stopped
  bff:
    image: openjdk:17
    container_name: bff
    ports:
      - "8081:8081"
    volumes:
      - /tmp/bff.jar:/app/app.jar
    command: java -jar /app/app.jar
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    restart: unless-stopped
  api-gateway:
    image: openjdk:17
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - /tmp/api-gateway.jar:/app/app.jar
    command: java -jar /app/app.jar
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka/
    restart: unless-stopped
