server.port=3003
spring.application.name=match-service

pet-service.url=${PET_SERVICE_URL:http://pet-service:3001}

# Resilience4j properties
resilience4j.circuitbreaker.instances.petServiceBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.petServiceBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.petServiceBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.petServiceBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.petServiceBreaker.permittedNumberOfCallsInHalfOpenState=3
