server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pet-service
          uri: http://pet-service:3001
          predicates:
            - Path=/api/pets/**
        - id: geo-service
          uri: http://geo-service:3002
          predicates:
            - Path=/api/locations/**
        - id: match-service
          uri: http://match-service:3003
          predicates:
            - Path=/api/matching/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.sanosysalvos: INFO